### ISSUE TITLE
Usable for watering?

### ISSUE THREAD

**Issue by asedwards96** [peckrob/petfeedd#11]
Will the program work also to dispense water into the bowl? I imagine I'd have to get a different new rotator that would be water tight.

**Comment by peckrob** [comment]
I don't see why you couldn't. Really all petfeedd is is a fancy GUI and a scheduler on top of gpiozero. When it reaches a certain time, it puts voltage on a pin for a certain amount of time, then turns it off. Which pin and how long the voltage is applied are all configurable.

I would probably recommend using a valve instead of trying to build a watertight rotor, you'll probably never be able to get something truly water tight. Possibly a sprinkler system irrigation valve (can be found at most hardware stores for around $15). Though most of those operate on 24 volt power so you'd need to provide an additional power source as you won't be able to use the RPi's onboard 5V power. You'll also need a relay.

**Comment by peckrob** [comment]
Version 1.0 explicitly includes support for using "Raw" devices now such as this. Feel free to open a new issue if this is not working for you.
